[tool.poetry]
name = "audioeditor"
version = "0.1.0"
description = ""
authors = ["Loraan <bfire2066@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
isort = "^5.12.0"
mypy = "^1.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
